import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>SpaceX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-8 py-6 bg-black min-h-screen">
        <h3 className="text-4xl text-center text-gray-700 font-bold">SpaceX</h3>
      </div>
    </div>
  );
}
